import type { ReceptionResult, SourceCard, Tradition } from "@/lib/bible/types";

export interface CuratedReceptionEntry {
  verseRef: string;
  sourceId: string;
  excerpt: string;
  theologicalNote?: string;
  voice: string;
  work: string;
  tradition: Tradition;
  citation: string;
  url?: string;
}

const CAUTION =
  "Verify quotations against the printed works. This desk is a study aid, not a teacher.";

function card(
  voice: string,
  work: string,
  tradition: Tradition,
  quote: string,
  citation: string,
  paraphrased = true,
  note?: string,
  url?: string,
): SourceCard {
  return { voice, work, tradition, quote, citation, paraphrased, note, url };
}

function desk(...cards: SourceCard[]): ReceptionResult {
  return { source: "curated", caution: CAUTION, cards };
}

const curated: Record<string, ReceptionResult> = {
  "JHN-1-1": desk(
    card(
      "Augustine",
      "Tractates on the Gospel of John 1",
      "patristic",
      "The Word was not made, for by the Word were all things made. This beginning has no beginning: the Word was.",
      "NPNF 1/7, Tractate 1 on John",
    ),
    card(
      "John Chrysostom",
      "Homilies on John 2",
      "patristic",
      "He said not ‘became,’ but ‘was’ — that you might understand His eternity, and that He is not later than the Father.",
      "NPNF 1/14, Homily 2 on John",
    ),
    card(
      "John Calvin",
      "Commentary on John 1:1",
      "reformed",
      "The Evangelist calls the Son of God the Word, because He is the eternal wisdom and will of God, and the lively image of His purpose.",
      "Calvin, Comm. John 1:1",
    ),
    card(
      "Westminster Confession",
      "Chapter 8.2",
      "confession",
      "The Son of God, the second person in the Trinity, being very and eternal God, of one substance and equal with the Father, did, when the fullness of time was come, take upon Him man's nature.",
      "WCF 8.2",
      false,
    ),
  ),
  "JHN-1-3": desk(
    card(
      "Athanasius",
      "Against the Arians 2",
      "patristic",
      "If all things were made through Him, He is not one of the things made. The Maker is other than the made.",
      "Athanasius, Orations against the Arians 2",
    ),
    card(
      "John Calvin",
      "Commentary on John 1:3",
      "reformed",
      "The Evangelist ascribes to the Word an office which belongs to God alone, that we may know Him to be the same God who was from the beginning.",
      "Calvin, Comm. John 1:3",
    ),
  ),
  "JHN-1-4": desk(
    card(
      "Augustine",
      "Tractates on John 1",
      "patristic",
      "What was made, in Him was life. The Word is not merely the artisan of creatures; He is their life, and that life is our light.",
      "NPNF 1/7, Tractate 1 on John",
    ),
    card(
      "Cyril of Alexandria",
      "Commentary on John 1",
      "patristic",
      "The life that is in the Word is not animal life, but the life by which the reasonable creature is made to live unto God.",
      "Cyril of Alexandria, In Joannem 1",
    ),
  ),
  "JHN-1-5": desk(
    card(
      "John Chrysostom",
      "Homilies on John 5",
      "patristic",
      "The light shines in the darkness — not that it may be overcome, but that it may scatter. The darkness did not master it.",
      "NPNF 1/14, Homily 5 on John",
    ),
    card(
      "John Calvin",
      "Commentary on John 1:5",
      "reformed",
      "The light is not extinguished though the world is blind. The fault is in the darkness, not in the light.",
      "Calvin, Comm. John 1:5",
    ),
  ),
  "JHN-1-12": desk(
    card(
      "Augustine",
      "Tractates on John 2",
      "patristic",
      "He gave them power to become children of God — not by nature, as the Only-Begotten, but by grace, by receiving Him.",
      "NPNF 1/7, Tractate 2 on John",
    ),
    card(
      "Martin Luther",
      "Sermons on John",
      "lutheran",
      "Faith is the receiving. They who believe in His name are born not of blood, but of God.",
      "Luther, sermons on John 1",
    ),
    card(
      "Heidelberg Catechism",
      "Q&A 33",
      "confession",
      "Christ alone is the eternal, natural Son of God; we are adopted children of God by grace, through Christ.",
      "Heidelberg Catechism 33",
      false,
    ),
  ),
  "JHN-1-14": desk(
    card(
      "Athanasius",
      "On the Incarnation",
      "patristic",
      "He was made man that we might be made God; and He manifested Himself by a body that we might receive the idea of the unseen Father.",
      "Athanasius, De Incarnatione 54",
    ),
    card(
      "Martin Luther",
      "Sermons on John",
      "lutheran",
      "The Word became flesh — not an appearance of flesh, but true human nature, that He might be our brother and our Savior.",
      "Luther, sermons on John 1",
    ),
    card(
      "John Calvin",
      "Commentary on John 1:14",
      "reformed",
      "The Word of God became truly man, yet remained what He was, that the two natures might constitute one Christ.",
      "Calvin, Comm. John 1:14",
    ),
  ),
  "JHN-1-18": desk(
    card(
      "Augustine",
      "Tractates on John 3",
      "patristic",
      "No one has seen God at any time — not with the eyes of the flesh. The only-begotten, who is in the bosom of the Father, He has declared Him.",
      "NPNF 1/7, Tractate 3 on John",
    ),
    card(
      "John Chrysostom",
      "Homilies on John 15",
      "patristic",
      "The bosom of the Father denotes closeness of essence, not a place. He who is there declares what He has seen.",
      "NPNF 1/14, Homily 15 on John",
    ),
  ),
  "JHN-1-29": desk(
    card(
      "John Chrysostom",
      "Homilies on John 17",
      "patristic",
      "He says not ‘a lamb,’ but ‘the Lamb,’ and adds ‘of God’ — the one of whom the law was a shadow, who takes away not one man’s sin but the world’s.",
      "NPNF 1/14, Homily 17 on John",
    ),
    card(
      "John Calvin",
      "Commentary on John 1:29",
      "reformed",
      "The Lamb is a sacrificial title. John sends us to the atonement, that we may not dream of any other way of taking away sin.",
      "Calvin, Comm. John 1:29",
    ),
    card(
      "Heidelberg Catechism",
      "Q&A 37",
      "confession",
      "That all the time He lived on earth, but especially at the end of His life, He bore, in body and soul, the wrath of God against the sin of the whole human race.",
      "Heidelberg Catechism 37",
      false,
    ),
  ),
  "JHN-3-16": desk(
    card(
      "Augustine",
      "Tractates on John 12",
      "patristic",
      "God loved the world — not that He found it worthy, but that He might make it worthy. The gift is the Son; the way is believing.",
      "NPNF 1/7, Tractate 12 on John",
    ),
    card(
      "John Calvin",
      "Commentary on John 3:16",
      "reformed",
      "Faith is not a merit that procures life, but the bucket that draws the water already given. Life is in the only-begotten, not in our believing.",
      "Calvin, Comm. John 3:16",
    ),
    card(
      "Martin Luther",
      "Sermons on John 3",
      "lutheran",
      "These words are the gospel in a nutshell: the Father’s love, the Son given, the world in view, eternal life by faith and not by works.",
      "Luther, sermons on John 3",
    ),
  ),
  "JHN-14-6": desk(
    card(
      "Cyril of Alexandria",
      "Commentary on John 9",
      "patristic",
      "He is not one way among many. He is the way because He is the truth, and the truth because He is the life — one Christ, not three paths.",
      "Cyril of Alexandria, In Joannem 9",
    ),
    card(
      "John Calvin",
      "Commentary on John 14:6",
      "reformed",
      "No man comes to the Father but by the Son. They who seek God apart from Christ wander, however religious the search.",
      "Calvin, Comm. John 14:6",
    ),
    card(
      "Westminster Confession",
      "Chapter 10.4",
      "confession",
      "Others, not elected, although they may be called by the ministry of the Word, cannot be saved: much less can men not professing the Christian religion be saved in any other way whatsoever.",
      "WCF 10.4 (abridged)",
    ),
  ),
  "MRK-1-1": desk(
    card(
      "Irenaeus",
      "Against Heresies 3.10",
      "patristic",
      "Mark, the interpreter of Peter, begins with the prophetic voice and names Jesus Christ the Son of God — the gospel’s first article.",
      "Irenaeus, Adv. Haer. 3.10–11",
    ),
    card(
      "Augustine",
      "Harmony of the Gospels 1",
      "patristic",
      "Mark is brief, as a lion’s roar is brief. He opens not with genealogy but with power: the beginning of the good news.",
      "Augustine, De Consensu Evangelistarum 1",
    ),
    card(
      "John Calvin",
      "Commentary on Mark 1:1",
      "reformed",
      "The gospel is not a new law but the glad tidings of the Son. Mark’s title is a sermon: Jesus, the Christ, the Son of God.",
      "Calvin, Comm. Mark 1:1",
    ),
  ),
  "MRK-1-11": desk(
    card(
      "Augustine",
      "Sermons on the New Testament",
      "patristic",
      "The Trinity is disclosed at the Jordan: the Son baptized, the Spirit descending, the Father’s voice. One God, three who speak and act.",
      "Augustine, sermons on the baptism of Christ",
    ),
    card(
      "John Chrysostom",
      "Homilies on Matthew 12",
      "patristic",
      "‘Beloved’ is not a later reward but an eternal name. The Father does not begin to love the Son at the river.",
      "NPNF 1/10, Homily 12 on Matthew",
    ),
    card(
      "Belgic Confession",
      "Article 9",
      "confession",
      "All this we know, as well from the testimonies of Holy Writ as from their operations, and chiefly by those we feel in ourselves. The Father is called our Creator, by His power; the Son is our Savior and Redeemer, by His blood; the Holy Ghost is our Sanctifier, by His dwelling in our hearts.",
      "Belgic Confession 9 (abridged)",
    ),
  ),
  "MRK-1-15": desk(
    card(
      "Origen",
      "Commentary on Matthew / fragments on Mark",
      "patristic",
      "The kingdom is at hand because the King is at hand. Repentance is not gloom but a turning of the mind toward the near reign of God.",
      "Origen, on the kingdom",
    ),
    card(
      "John Calvin",
      "Commentary on Mark 1:15",
      "reformed",
      "Faith and repentance are the two hinges of the gospel call. The time is fulfilled: delay is unbelief.",
      "Calvin, Comm. Mark 1:15",
    ),
    card(
      "Heidelberg Catechism",
      "Q&A 88–90",
      "confession",
      "True repentance or conversion is the dying of the old man and the coming to life of the new — a sincere sorrow for sin and a hearty joy in God through Christ.",
      "Heidelberg Catechism 88–90 (abridged)",
    ),
  ),
  "MRK-1-17": desk(
    card(
      "Bede",
      "Exposition of Mark",
      "patristic",
      "They leave nets that catch fish to become fishers of men. The craft is the same in figure: patience, risk, and a catch that is not their own.",
      "Bede, In Marcum 1",
    ),
    card(
      "John Calvin",
      "Commentary on Mark 1:17",
      "reformed",
      "Christ does not ask them to invent a ministry. He makes them what they were not. The call creates the fishermen.",
      "Calvin, Comm. Mark 1:16–17",
    ),
  ),
  "MAT-1-21": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily IV)",
      "eastern-patristic",
      "He shall save His people; not the Jewish people only, but the whole world that comes to Him. He says not 'from visible enemies or tyrants,' but 'from their sins' — a warfare of soul, requiring divine power.",
      "NPNF 1/10, Homily 4 on Matthew",
      true,
      "Chrysostom emphasizes the angelic announcement distinguishing Christ's spiritual salvation from nationalistic messianic expectations.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "The name Jesus signifies Savior. The angel announces that He will redeem His people from their sins, correcting the common error of the Jews who looked for an earthly monarch to deliver them from Roman servitude.",
      "Calvin, Comm. Matt. 1:21",
      true,
      "Calvin highlights Christ as Savior from spiritual guilt and bondage, refuting carnal expectations of a temporal kingdom.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Matthew Poole",
      "Annotations upon the Holy Bible",
      "puritan",
      "His name is called Jesus, a Savior, because he saves from the guilt, power, and punishment of sin; not by a temporal deliverance, but by eternal redemption.",
      "Poole, Annotations on Matt. 1:21",
      true,
      "Poole expounds the triple deliverance of justification, sanctification, and glorification.",
      "https://www.ccel.org/ccel/poole/annotations.html",
    ),
  ),
  "MAT-1-22": desk(
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Jerome says: 'That it might be fulfilled which was spoken of the Lord by the prophet. Not that the event happened only that the prophecy might be fulfilled, but that the prophet foresaw the future and the divine decree was accomplished.'",
      "Aquinas, Catena Aurea, Matt. 1:22",
      true,
      "Scholastic synthesis on divine sovereignty, prophecy, and teleological fulfillment in Christ.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Matthew shows that nothing came to pass by chance, but that this marvelous work of God had been foretold long before by the prophet Isaiah.",
      "Calvin, Comm. Matt. 1:22",
      true,
      "The unity of Old Testament prophetic promise and New Testament fulfillment.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
  ),
  "MAT-1-23": desk(
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Jerome says: The Hebrew word alma signifies a virgin hidden and kept secret. Augustine adds: She who conceived without concupiscence remained a virgin in bearing and after bearing. He is truly Immanuel, God with us in the assumption of our flesh.",
      "Aquinas, Catena Aurea, Matt. 1:22–23",
      true,
      "Aquinas compiles Patristic consensus from Jerome and Augustine affirming the perpetual virginity and the hypostatic union in Isaiah 7:14.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily V)",
      "eastern-patristic",
      "They shall call His name Immanuel, which is, God with us. He did not say 'thou shalt call,' but 'they shall call' — that is, the events and deeds shall proclaim Him God with us.",
      "NPNF 1/10, Homily 5 on Matthew",
      true,
      "Chrysostom on the divine identity of the incarnate Word manifest in His works.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "God has descended to us that we might ascend to Him; by taking our flesh He has united our lowliness with the divine majesty. Immanuel is not a bare title, but the substance of our salvation.",
      "Calvin, Comm. Matt. 1:23",
      true,
      "Calvin on the mediator uniting divine majesty with human flesh.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Matthew Poole",
      "Annotations upon the Holy Bible",
      "puritan",
      "Immanuel: God with us, not only by his essential presence, but by personal union, God and man in one person; and covenantally, reconciling God to man by his blood.",
      "Poole, Annotations on Matt. 1:23",
      true,
      "Poole expounds Immanuel as the mediator of the covenant of grace in two natures.",
      "https://www.ccel.org/ccel/poole/annotations.html",
    ),
  ),
  "MAT-5-3": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XV)",
      "eastern-patristic",
      "What is 'poor in spirit'? The humble and contrite in mind. As pride was the root of all wickedness, Christ sets humility as the first foundation of virtue; unless this be laid, whatever virtues you build will fall.",
      "NPNF 1/10, Homily 15 on Matthew",
      true,
      "Humility as the foundation of virtue.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Augustine explains: The proud seek after an earthly kingdom; the poor in spirit, who are not puffed up with the pride of riches or knowledge, possess the kingdom of heaven. Jerome adds: Those who are voluntary in poverty for the Spirit's sake.",
      "Aquinas, Catena Aurea, Matt. 5:3",
      true,
      "Interior detachment and poverty of spirit over self-glory.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Those are poor in spirit who, brought to nothing in themselves and terrified by the consciousness of their spiritual poverty, betake themselves to the mercy of God. For grace is poured only into empty vessels.",
      "Calvin, Comm. Matt. 5:3",
      true,
      "Radical reduction to self-despair to receive sovereign grace.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Martin Luther",
      "Commentary on the Sermon on the Mount",
      "lutheran",
      "To be poor in spirit does not mean begging or walking barefoot, but holding oneself destitute before God, having no trust in one's own righteousness, and clinging solely to Christ's promise by faith.",
      "Luther, Comm. Sermon on the Mount (1532), Matt. 5:3",
      true,
      "Faith grasping Christ outside human boasting.",
      "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
    ),
    card(
      "Gregory of Nyssa",
      "Homilies on the Beatitudes 1",
      "patristic",
      "Poverty of spirit is not want of goods but the soul emptied of pride, so that the kingdom may have room.",
      "Gregory of Nyssa, De Beatitudinibus 1",
    ),
  ),
  "MAT-5-4": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XV)",
      "eastern-patristic",
      "He blesses not simply those who mourn, but those who mourn for their sins. For worldly grief brings death, but godly sorrow works repentance unto salvation.",
      "NPNF 1/10, Homily 15 on Matthew",
      true,
      "Godly sorrow over transgression vs worldly grief.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ comforts those who groan under the burden of sin and afflictions, assuring them that their tears are gathered by God, who will wipe away all weeping.",
      "Calvin, Comm. Matt. 5:4",
      true,
      "Spiritual mourning finding consolation in divine pardon.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
  ),
  "MAT-5-5": desk(
    card(
      "Augustine",
      "Our Lord's Sermon on the Mount 1",
      "western-patristic",
      "The meek are those who do not resist divine reproof in scripture, but yield themselves to God's Word in silence and reverence. The earth they inherit is the eternal inheritance of the saints.",
      "NPNF 1/6, De Sermone Domini 1.2",
      true,
      "Meekness yielding to the authority of divine revelation.",
      "https://www.ccel.org/ccel/schaff/npnf106.html",
    ),
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Meekness curbs anger and bridles turbulent passions, so that the soul remains tranquil and fit to receive divine wisdom.",
      "Aquinas, Catena Aurea, Matt. 5:5",
      true,
      "The virtue of meekness subduing anger for spiritual discernment.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
  ),
  "MAT-5-6": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XV)",
      "eastern-patristic",
      "He does not say 'blessed are they who seek righteousness,' but 'who hunger and thirst for it' — exhibiting an insatiable craving that will not be turned aside.",
      "NPNF 1/10, Homily 15 on Matthew",
      true,
      "Passionate longing for evangelical holiness.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "Martin Luther",
      "Commentary on the Sermon on the Mount",
      "lutheran",
      "This hunger is the appetite of faith, which knows its own unworthiness and pants after the righteousness of Christ given freely in the gospel.",
      "Luther, Comm. Sermon on the Mount, Matt. 5:6",
      true,
      "The appetite of faith hungering for imputed righteousness.",
      "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
    ),
  ),
  "MAT-5-7": desk(
    card(
      "Gregory of Nyssa",
      "Homilies on the Beatitudes 5",
      "eastern-patristic",
      "Mercy is the parent of affection, the guarantee of love, and the image of the divine nature itself. He who shows mercy puts on the likeness of God.",
      "Gregory of Nyssa, De Beatitudinibus 5",
      true,
      "Mercy as the reflection of the divine character.",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ declares that none can hope for God's mercy who have hardened their bowels against the miseries of their brethren.",
      "Calvin, Comm. Matt. 5:7",
      true,
      "Active compassion as the necessary evidence of receiving divine mercy.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
  ),
  "MAT-5-8": desk(
    card(
      "Augustine",
      "Our Lord's Sermon on the Mount 1",
      "western-patristic",
      "How foolish are they who seek God with external eyes! He is seen with the heart, when the heart is purged of earthly defilement by love.",
      "NPNF 1/6, De Sermone Domini 1.4",
      true,
      "The single eye of a purified heart perceiving the unseen God.",
      "https://www.ccel.org/ccel/schaff/npnf106.html",
    ),
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Purity of heart is the disposition for the beatific vision, wherein the intellect is illuminated by the light of glory to see God as He is.",
      "Aquinas, Catena Aurea, Matt. 5:8",
      true,
      "The beatific vision requires purification from disordered affections.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
  ),
  "MAT-5-9": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XV)",
      "eastern-patristic",
      "The peacemakers not only live in peace themselves, but reconcile enemies, imitating the only-begotten Son who reconciled a fallen race to God.",
      "NPNF 1/10, Homily 15 on Matthew",
      true,
      "Reconciliation between alienated souls reflecting Christ's mediation.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ praises those who study peace, even when provoked; yet true peace can never be bought by surrendering divine truth.",
      "Calvin, Comm. Matt. 5:9",
      true,
      "Evangelical peacemaking rooted in truth without compromise.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
  ),
  "MAT-5-10": desk(
    card(
      "Augustine",
      "Our Lord's Sermon on the Mount 1",
      "western-patristic",
      "Notice the condition: 'for righteousness' sake.' It is not the punishment that makes the martyr, but the cause.",
      "NPNF 1/6, De Sermone Domini 1.5",
      true,
      "The cause of righteousness alone consecrates suffering for Christ.",
      "https://www.ccel.org/ccel/schaff/npnf106.html",
    ),
    card(
      "Martin Luther",
      "Commentary on the Sermon on the Mount",
      "lutheran",
      "If you preach Christ and stand on His Word, the world cannot endure you. Persecution is the infallible badge of faithful discipleship.",
      "Luther, Comm. Sermon on the Mount, Matt. 5:10",
      true,
      "Cross-bearing as the inseparable companion of the confessing gospel.",
      "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
    ),
  ),
  "MAT-5-17": desk(
    card(
      "Augustine",
      "Our Lord's Sermon on the Mount 1.8",
      "western-patristic",
      "He fulfills the law either by doing what it commanded, or by supplying what was lacking, or by granting grace whereby its righteousness might be lived. The Law was given to convict; grace is given to fulfill.",
      "NPNF 1/6, De Sermone Domini 1.8",
      true,
      "The Law reveals transgressions and convicts; grace enables true spiritual fulfillment through love.",
      "https://www.ccel.org/ccel/schaff/npnf106.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ confirms the permanent authority of the Law. The doctrine of the Gospel does not detract from the Law, but establishes its true scope. Christ fulfills it by his perfect obedience, by his expiation on the cross, and by writing it on our hearts.",
      "Calvin, Comm. Matt. 5:17",
      true,
      "Harmony of Law and Gospel; three uses of the Law.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Martin Luther",
      "Commentary on the Sermon on the Mount",
      "lutheran",
      "Christ alone fulfills the demands of the Law on our behalf, bearing its curse and rendering the full satisfaction that no sinner could ever yield. Hence our righteousness is alien, found in Him alone.",
      "Luther, Comm. Sermon on the Mount (1532), Matt. 5:17",
      true,
      "Active and passive obedience of Christ fulfilling the Law for justification.",
      "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
    ),
  ),
  "MAT-5-18": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XVI)",
      "eastern-patristic",
      "Not one jot or tittle shall pass away. Do you see how small the letters He mentions? Indicating that even the least details of scripture carry divine weight and fulfillment.",
      "NPNF 1/10, Homily 16 on Matthew",
      true,
      "The immutable authority and total truthfulness of God's Word.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "There is nothing in the Law that is useless or superfluous; all its promises and moral precepts shall remain inviolate until the end of the world.",
      "Calvin, Comm. Matt. 5:18",
      true,
      "Perpetual validity of the moral law and prophetic promises.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
  ),
  "MAT-5-19": desk(
    card(
      "Augustine",
      "Our Lord's Sermon on the Mount 1.9",
      "western-patristic",
      "He who breaks one of these least commandments and teaches men so will be called least in the kingdom of heaven; that is, will have no place in the kingdom of life.",
      "NPNF 1/6, De Sermone Domini 1.9",
      true,
      "The danger of teaching laxity regarding God's moral law.",
      "https://www.ccel.org/ccel/schaff/npnf106.html",
    ),
    card(
      "Matthew Poole",
      "Annotations upon the Holy Bible",
      "puritan",
      "Christ here rebukes the corrupt scribes who distinguished between great and small precepts, neglecting the moral duties while magnifying ceremonial traditions.",
      "Poole, Annotations on Matt. 5:19",
      true,
      "Against antinomian laxity and rabbinic diminishment of moral obligations.",
      "https://www.ccel.org/ccel/poole/annotations.html",
    ),
  ),
  "MAT-5-20": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XVI)",
      "eastern-patristic",
      "Unless your righteousness exceeds that of the scribes and Pharisees: they observed outward rites, but Christ demands inward purity, rooting out the desire for sin before it breaks into deed.",
      "NPNF 1/10, Homily 16 on Matthew",
      true,
      "Inward holiness surpassing external formalism.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "The Pharisees were content with an external mask of sanctity. Christ requires sincere integrity of heart, showing that true righteousness begins in the inner man.",
      "Calvin, Comm. Matt. 5:20",
      true,
      "Spiritual obedience vs hypocrisy and external legalism.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Martin Luther",
      "Commentary on the Sermon on the Mount",
      "lutheran",
      "The righteousness of the Pharisees was a self-righteous mask that sought merit before God. The righteousness of the Kingdom is faith that receives Christ and brings forth genuine fruits of love.",
      "Luther, Comm. Sermon on the Mount, Matt. 5:20",
      true,
      "The righteousness of faith superseding hypocritical self-merit.",
      "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
    ),
  ),
  "MAT-6-9": desk(
    card(
      "Tertullian",
      "On Prayer",
      "patristic",
      "He who is Father may also be called upon as Lord, yet Christ would have us begin with Father, that affection might lead the prayer.",
      "Tertullian, De Oratione 2–3",
    ),
    card(
      "Cyprian",
      "On the Lord’s Prayer",
      "patristic",
      "We do not say ‘My Father’ but ‘Our Father,’ because the prayer is the prayer of a people, and none prays for himself alone.",
      "Cyprian, De Dominica Oratione 8–9",
    ),
    card(
      "Martin Luther",
      "Large Catechism",
      "lutheran",
      "God would by these words tenderly invite us to believe that He is our true Father and that we are His true children, so that we may ask Him with all cheerfulness.",
      "Luther, Large Catechism, Lord’s Prayer",
    ),
  ),
  "MAT-16-16": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily LIV)",
      "eastern-patristic",
      "Peter confesses: 'Thou art the Christ, the Son of the living God.' He says not 'a son' by grace, but 'the Son' by nature, declaring His eternal and proper deity.",
      "NPNF 1/10, Homily 54 on Matthew",
      true,
      "Peter confesses Christ's genuine Sonship by divine nature.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Peter's confession contains the sum of our faith: that Jesus is the Messiah promised of old, and that He is true God, the fountain of eternal life.",
      "Calvin, Comm. Matt. 16:16",
      true,
      "The bedrock confession of Jesus as Messiah and divine Savior.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
  ),
  "MAT-16-17": desk(
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Flesh and blood hath not revealed it unto thee, but my Father which is in heaven. Hilary says: He is blessed who receives praise for looking beyond human eyes to see the Son of God by the revelation of the Father.",
      "Aquinas, Catena Aurea, Matt. 16:17",
      true,
      "Divine illuminating grace over human reasoning.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily LIV)",
      "eastern-patristic",
      "Christ shows that Peter's knowledge was not of human deduction, but a divine gift communicated directly from the Father.",
      "NPNF 1/10, Homily 54 on Matthew",
      true,
      "The revelation of the Father granting knowledge of the Son.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
  ),
  "MAT-16-18": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily LIV)",
      "eastern-patristic",
      "'On this rock I will build my church' — that is, on the faith of his confession. He did not say upon Peter, for he built His church not on a man, but on the faith of confessing Him as the Son of God.",
      "NPNF 1/10, Homily 54 on Matthew",
      true,
      "The rock is the faith of Peter's confession.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Augustine in his Retractations says: 'The rock was Christ, whom Simon confessed.' Yet Hilary and Leo show Peter rewarded for confessing Christ's divinity with apostolic primacy, that the unity of the Church might be preserved against the gates of hell.",
      "Aquinas, Catena Aurea, Matt. 16:18",
      true,
      "Aquinas compiles Latin and Greek consensus synthesizing Christ as the foundational rock and Peter's confession.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ applies the title of rock not to Peter's person, but to the confession of faith which he uttered. Christ is the only foundation; whoever rests on Peter's person rather than on Christ confesses a mortal foundation that cannot withstand the gates of hell.",
      "Calvin, Comm. Matt. 16:18",
      true,
      "Exegetes the rock as Christ and the confession of Him, refuting papal succession.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Matthew Poole",
      "Annotations upon the Holy Bible",
      "puritan",
      "Upon this rock: either Christ himself, or the doctrine and confession Peter made of him. Upon this rock Christ builds his church, and all the powers of darkness shall never overthrow it.",
      "Poole, Annotations on Matt. 16:18",
      true,
      "The Church founded on the doctrinal truth of Christ confessed.",
      "https://www.ccel.org/ccel/poole/annotations.html",
    ),
  ),
  "MAT-28-18": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XC)",
      "eastern-patristic",
      "'All power is given unto me in heaven and in earth.' He speaks this according to His human nature, which He assumed for our salvation; as God He possessed all things eternally, but now as our victorious Head He receives all dominion.",
      "NPNF 1/10, Homily 90 on Matthew",
      true,
      "Apostolic empowerment and divine omnipresence.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ claims universal dominion over heaven and earth, not that He began to reign only then as God, but that as Mediator He was inaugurated as King over all creatures. By this authority He commissions the preaching of the Word and the administration of Sacraments.",
      "Calvin, Comm. Matt. 28:18–20",
      true,
      "The universal domain of Christ and the authority of Word and Sacraments.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Matthew Poole",
      "Annotations upon the Holy Bible",
      "puritan",
      "All power is given unto me: a supreme, sovereign, universal power as Mediator to conquer enemies, forgive sins, call the Gentiles, and govern His church.",
      "Poole, Annotations on Matt. 28:18",
      true,
      "The sovereign mediatorial power of the risen Lord.",
      "https://www.ccel.org/ccel/poole/annotations.html",
    ),
  ),
  "MAT-28-19": desk(
    card(
      "Basil the Great",
      "On the Holy Spirit 10",
      "eastern-patristic",
      "We are baptized into the name, not the names — one name of Father, Son, and Holy Spirit, that the distinction of persons may not break the unity of Godhead.",
      "NPNF 2/8, De Spiritu Sancto 10",
    ),
    card(
      "John Calvin",
      "Commentary on Matthew 28:19",
      "reformed",
      "The command is to make disciples, not mere hearers; baptism is the seal of that teaching, in the name of the Triune God.",
      "Calvin, Comm. Matt. 28:19",
      true,
      "Discipling the nations through the ministry of the Word and baptism.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Thomas Aquinas",
      "Catena Aurea on Matthew",
      "scholastic",
      "Jerome says: They first teach all nations, then dip those who are taught in water. For the body cannot receive the sacrament of baptism unless the soul has before received the truth of the faith.",
      "Aquinas, Catena Aurea, Matt. 28:19",
      true,
      "Catechesis precedes sacramental baptism in the apostolic mandate.",
      "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
    ),
    card(
      "Nicene Creed",
      "Constantinople 381",
      "confession",
      "We believe in one God, the Father Almighty… and in one Lord Jesus Christ… and in the Holy Spirit, the Lord and Giver of life, who proceeds from the Father, who with the Father and the Son together is worshiped and glorified.",
      "Niceno-Constantinopolitan Creed (abridged)",
      false,
    ),
  ),
  "MAT-28-20": desk(
    card(
      "John Chrysostom",
      "Homilies on Matthew (Homily XC)",
      "eastern-patristic",
      "'Lo, I am with you always, even unto the end of the world.' Do you mark His power and authority? He speaks not to the disciples only, but to all who should believe after them. He is present not by bodily appearance, but by divine majesty and grace.",
      "NPNF 1/10, Homily 90 on Matthew",
      true,
      "Apostolic empowerment and divine omnipresence continuing to the consummation.",
      "https://www.ccel.org/ccel/schaff/npnf110.html",
    ),
    card(
      "John Calvin",
      "Commentary on a Harmony of the Evangelists",
      "reformed",
      "Christ promises that He will never abandon His church. Though removed from our sight into heaven, He is present by the power of His Spirit to defend and preserve His people against all adversaries.",
      "Calvin, Comm. Matt. 28:20",
      true,
      "Perpetual spiritual presence of Christ sustaining the Church.",
      "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
    ),
    card(
      "Matthew Poole",
      "Annotations upon the Holy Bible",
      "puritan",
      "I am with you alway: not in body, but by my Spirit, my grace, my providence, and my blessing, upholding the ministry of the gospel to the end of time.",
      "Poole, Annotations on Matt. 28:20",
      true,
      "The comforting promise of spiritual guidance and protection.",
      "https://www.ccel.org/ccel/poole/annotations.html",
    ),
  ),
  "LUK-2-11": desk(
    card(
      "Leo the Great",
      "Sermon 21 on the Nativity",
      "patristic",
      "He is born a Savior, who is Christ the Lord — not one title stacked on another, but one person who is both the Anointed and the Lord.",
      "NPNF 2/12, Sermon 21",
    ),
    card(
      "Martin Luther",
      "Christmas sermons",
      "lutheran",
      "Unto you is born — not unto angels, not in general, but unto you. Faith takes the pronoun as its own.",
      "Luther, Christmas sermons on Luke 2",
    ),
  ),
  "GEN-1-1": desk(
    card(
      "Basil the Great",
      "Hexaemeron 1",
      "patristic",
      "‘In the beginning God created’ — the origin of time, the foundation of the world, so that what is seen might not be thought eternal.",
      "NPNF 2/8, Hexaemeron Homily 1",
    ),
    card(
      "John Calvin",
      "Commentary on Genesis 1:1",
      "reformed",
      "Moses does not philosophize, but simply states that the world is not eternal, and that God is its Maker.",
      "Calvin, Comm. Gen. 1:1",
    ),
    card(
      "Westminster Confession",
      "Chapter 4.1",
      "confession",
      "It pleased God the Father, Son, and Holy Ghost, for the manifestation of the glory of His eternal power, wisdom, and goodness, in the beginning, to create, or make of nothing, the world.",
      "WCF 4.1",
      false,
    ),
  ),
  "GEN-1-26": desk(
    card(
      "Gregory of Nyssa",
      "On the Making of Man",
      "patristic",
      "Let us make: the counsel is plural, the image is one. Man is not the image of a part of God, but of God.",
      "Gregory of Nyssa, De Hominis Opificio",
    ),
    card(
      "Augustine",
      "The Literal Meaning of Genesis 3",
      "patristic",
      "The image is in the inner man — memory, understanding, will — a created trinity, not a second God.",
      "Augustine, De Genesi ad litteram 3",
    ),
    card(
      "John Calvin",
      "Commentary on Genesis 1:26",
      "reformed",
      "The image of God is not the body, though the body is not excluded from dignity. It is the integrity of the soul as it mirrored its Maker before the fall.",
      "Calvin, Comm. Gen. 1:26",
    ),
  ),
  "GEN-1-27": desk(
    card(
      "Basil the Great",
      "Hexaemeron 9",
      "patristic",
      "Male and female He created them: the image is not assigned to one sex. Dominion is a shared charge, not a license to devour.",
      "NPNF 2/8, Hexaemeron Homily 9",
    ),
    card(
      "Westminster Confession",
      "Chapter 4.2",
      "confession",
      "After God had made all other creatures, He created man, male and female, with reasonable and immortal souls, endued with knowledge, righteousness, and true holiness, after His own image.",
      "WCF 4.2",
      false,
    ),
  ),
  "GEN-3-15": desk(
    card(
      "Irenaeus",
      "Against Heresies 3.23",
      "patristic",
      "The seed of the woman is Christ. He recapitulutes the long war, crushing the serpent’s head while His heel is wounded.",
      "Irenaeus, Adv. Haer. 3.23",
    ),
    card(
      "Martin Luther",
      "Lectures on Genesis",
      "lutheran",
      "This is the first gospel. Adam and Eve heard not only a curse but a promise, and they lived by that promise until the Seed came.",
      "Luther, Lectures on Genesis 3",
    ),
    card(
      "John Calvin",
      "Commentary on Genesis 3:15",
      "reformed",
      "God does not leave the serpent a truce. The victory is promised in the woman’s seed, that faith might have an object from the first day of the fall.",
      "Calvin, Comm. Gen. 3:15",
    ),
  ),
  "EXO-3-14": desk(
    card(
      "Augustine",
      "Tractates on John 38",
      "patristic",
      "I AM WHO I AM: He names Himself as being, not as becoming. Other things are; He is He who is.",
      "NPNF 1/7, Tractate 38 on John",
    ),
    card(
      "Thomas Aquinas",
      "Summa Theologiae I q.13",
      "catholic",
      "This name, HE WHO IS, is the most proper name of God, for it signifies not a form but existence itself.",
      "ST I q.13 a.11 (paraphrased)",
    ),
    card(
      "John Calvin",
      "Commentary on Exodus 3:14",
      "reformed",
      "God opposes His eternal being to the idols that are not. The name is a shield to Moses, and a rebuke to Egypt.",
      "Calvin, Comm. Exod. 3:14",
    ),
  ),
  "PSA-23-1": desk(
    card(
      "Augustine",
      "Expositions on the Psalms 23",
      "patristic",
      "The Lord is my shepherd: I shall not want, because I am a sheep of His, not of my own keeping.",
      "Augustine, Enarr. Ps. 23",
    ),
    card(
      "John Calvin",
      "Commentary on Psalm 23",
      "reformed",
      "David does not boast of his store, but of his Shepherd. Want is banished not by plenty but by the care of God.",
      "Calvin, Comm. Ps. 23:1",
    ),
  ),
  "PSA-23-4": desk(
    card(
      "Athanasius",
      "Letter to Marcellinus on the Psalms",
      "patristic",
      "In the valley of the shadow the psalm is a staff. Christ has walked that valley, so the sheep need not fear it as an end.",
      "Athanasius, Ad Marcellinum",
    ),
    card(
      "Matthew Henry",
      "Commentary on Psalm 23",
      "reformed",
      "Death is a shadow, and a shadow cannot hurt. The rod and staff comfort because they belong to the Shepherd who is there.",
      "Henry, Comm. Ps. 23:4",
    ),
  ),
  "PSA-119-105": desk(
    card(
      "Augustine",
      "Expositions on the Psalms 119",
      "patristic",
      "The word is a lamp, not that we may see it, but that by it we may see ourselves and the way.",
      "Augustine, Enarr. Ps. 119",
    ),
    card(
      "Matthew Henry",
      "Commentary on Psalm 119",
      "reformed",
      "The word of God directs us in our work and way, and a dark place indeed the world would be without it.",
      "Henry, Comm. Ps. 119:105",
    ),
  ),
  "ISA-7-14": desk(
    card(
      "Justin Martyr",
      "Dialogue with Trypho 66–68",
      "patristic",
      "The virgin conceives: Isaiah spoke of a sign, and Matthew reads it as fulfilled in Mary, not as a mere young woman of Ahaz’s court.",
      "Justin, Dial. 66–68",
    ),
    card(
      "John Chrysostom",
      "Homilies on Matthew 5",
      "patristic",
      "Emmanuel is not a private nickname. It is the gospel in one word: God with us — not in figure only, but in flesh.",
      "NPNF 1/10, Homily 5 on Matthew",
    ),
  ),
  "ISA-9-6": desk(
    card(
      "Irenaeus",
      "Against Heresies 3.16",
      "patristic",
      "A child is born, a son is given: born as man, given as God. The names that follow are not honors piled on a creature.",
      "Irenaeus, Adv. Haer. 3.16",
    ),
    card(
      "John Calvin",
      "Commentary on Isaiah 9:6",
      "reformed",
      "Wonderful, Counselor, Mighty God: the prophet will not let us rest in a merely human king. The government is upon His shoulder because He is more than David’s heir.",
      "Calvin, Comm. Isa. 9:6",
    ),
  ),
  "ISA-53-5": desk(
    card(
      "Justin Martyr",
      "Dialogue with Trypho 13",
      "patristic",
      "He was wounded for our transgressions: the prophet ascribes the stripes not to His fault but to ours, that we might be healed.",
      "Justin, Dial. 13",
    ),
    card(
      "John Calvin",
      "Commentary on Isaiah 53:5",
      "reformed",
      "The chastisement of our peace was upon Him. Peace is not cheap; it is purchased by His punishment in our place.",
      "Calvin, Comm. Isa. 53:5",
    ),
    card(
      "Heidelberg Catechism",
      "Q&A 37–39",
      "confession",
      "He bore the wrath of God against the sin of the whole human race… that He might redeem our body and soul from everlasting damnation, and obtain for us the grace of God, righteousness, and eternal life.",
      "Heidelberg Catechism 37–39 (abridged)",
    ),
  ),
  "ROM-1-16": desk(
    card(
      "John Chrysostom",
      "Homilies on Romans 2",
      "patristic",
      "He is not ashamed of the gospel, though the cross is a scandal. Power is not in the speaker’s dignity but in the message that saves.",
      "NPNF 1/11, Homily 2 on Romans",
    ),
    card(
      "Martin Luther",
      "Preface to Romans",
      "lutheran",
      "The gospel is a power, not a counsel. It does not tell us what we must do to become righteous; it gives the righteousness it names.",
      "Luther, Preface to Romans",
    ),
  ),
  "ROM-3-23": desk(
    card(
      "Augustine",
      "On Nature and Grace",
      "patristic",
      "All have sinned: not the nations only, nor the Jews only. There is no island of innocence from which we might bargain with God.",
      "Augustine, De Natura et Gratia",
    ),
    card(
      "John Calvin",
      "Commentary on Romans 3:23",
      "reformed",
      "The glory of God is the standard, not the neighbor. Measured so, every mouth is stopped.",
      "Calvin, Comm. Rom. 3:23",
    ),
    card(
      "Westminster Confession",
      "Chapter 6.2–4",
      "confession",
      "By this sin they fell from their original righteousness… and we in them. From this original corruption we are utterly indisposed, disabled, and made opposite to all good.",
      "WCF 6.2–4 (abridged)",
    ),
  ),
  "ROM-5-8": desk(
    card(
      "John Chrysostom",
      "Homilies on Romans 9",
      "patristic",
      "He did not wait for us to become worthy. While we were yet sinners — that is the measure of the love.",
      "NPNF 1/11, Homily 9 on Romans",
    ),
    card(
      "John Calvin",
      "Commentary on Romans 5:8",
      "reformed",
      "God commends His love in that Christ died not for the righteous but for the ungodly. The cause is in God, not in us.",
      "Calvin, Comm. Rom. 5:8",
    ),
  ),
  "ROM-8-1": desk(
    card(
      "John Chrysostom",
      "Homilies on Romans 13",
      "patristic",
      "He did not say ‘who do not sin,’ but ‘who are in Christ Jesus.’ The condemnation is taken off, not by our worthiness, but by the gift.",
      "NPNF 1/11, Homily 13 on Romans",
    ),
    card(
      "John Calvin",
      "Commentary on Romans 8:1",
      "reformed",
      "There is no condemnation to them, because they are grafted into the body of Christ. He does not exempt them from the remaining contest with sin, but from the guilt of it.",
      "Calvin, Comm. Rom. 8:1",
    ),
    card(
      "Heidelberg Catechism",
      "Q&A 60",
      "confession",
      "God, without any merit of mine, of mere grace, grants and imputes to me the perfect satisfaction, righteousness, and holiness of Christ.",
      "Heidelberg Catechism 60",
      false,
    ),
  ),
  "ROM-8-28": desk(
    card(
      "Augustine",
      "On the Gift of Perseverance",
      "patristic",
      "All things work together for good to those who love God — not that evil is good, but that God weaves even wounds into the good of His called.",
      "Augustine, De Dono Perseverantiae",
    ),
    card(
      "John Calvin",
      "Commentary on Romans 8:28",
      "reformed",
      "The promise is not for all men indiscriminately, but for the called according to purpose. Providence is paternal to the children.",
      "Calvin, Comm. Rom. 8:28",
    ),
  ),
  "1CO-15-3": desk(
    card(
      "Irenaeus",
      "Against Heresies 3.18",
      "patristic",
      "Christ died for our sins according to the Scriptures: the apostle hands on what he received, that the church might not invent another gospel.",
      "Irenaeus, Adv. Haer. 3.18",
    ),
    card(
      "John Chrysostom",
      "Homilies on 1 Corinthians 38",
      "patristic",
      "This is first of all. The resurrection stands on the death ‘for our sins’; empty the death of its purpose and the rising is a marvel without mercy.",
      "NPNF 1/12, Homily 38 on 1 Corinthians",
    ),
    card(
      "Nicene Creed",
      "Constantinople 381",
      "confession",
      "For our sake He was crucified under Pontius Pilate; He suffered and was buried. On the third day He rose again in accordance with the Scriptures.",
      "Niceno-Constantinopolitan Creed",
      false,
    ),
  ),
  "EPH-2-8": desk(
    card(
      "John Chrysostom",
      "Homilies on Ephesians 4",
      "patristic",
      "By grace you have been saved through faith — and this not of yourselves. He shuts every door of boasting, even the door of believing as if it were a work.",
      "NPNF 1/13, Homily 4 on Ephesians",
    ),
    card(
      "Martin Luther",
      "Lectures on Galatians / on grace",
      "lutheran",
      "Faith is the empty hand. Grace is the gift in it. If the hand boasts, it has closed.",
      "Luther, on Eph. 2 / Galatians",
    ),
    card(
      "Westminster Confession",
      "Chapter 11.1",
      "confession",
      "Those whom God effectually calls, He also freely justifies… not for anything wrought in them, or done by them, but for Christ’s sake alone.",
      "WCF 11.1 (abridged)",
      false,
    ),
  ),
  "PHP-2-6": desk(
    card(
      "Athanasius",
      "Against the Arians 1",
      "patristic",
      "Being in the form of God, He did not clutch at equality. He had it; the humility is in taking the form of a servant, not in ceasing to be God.",
      "Athanasius, Orations against the Arians 1",
    ),
    card(
      "Gregory of Nazianzus",
      "Oration 37 / Theological Orations",
      "patristic",
      "What He was, He remained; what He was not, He assumed. The emptying is addition of humanity, not subtraction of deity.",
      "Gregory of Nazianzus, orations on the Son",
    ),
    card(
      "Chalcedonian Definition",
      "Council of Chalcedon 451",
      "confession",
      "One and the same Son… acknowledged in two natures, without confusion, without change, without division, without separation.",
      "Definition of Chalcedon",
      false,
    ),
  ),
  "HEB-1-1": desk(
    card(
      "John Chrysostom",
      "Homilies on Hebrews 1",
      "patristic",
      "God spoke in many portions by the prophets; in these last days He has spoken by a Son. The difference is not of truth but of fullness.",
      "NPNF 1/14, Homily 1 on Hebrews",
    ),
    card(
      "John Calvin",
      "Commentary on Hebrews 1:1–2",
      "reformed",
      "Christ is the last and highest word. They who seek a later revelation after the Son are not going on; they are going back.",
      "Calvin, Comm. Heb. 1:1–2",
    ),
  ),
  "HEB-4-12": desk(
    card(
      "Origen",
      "Homilies on Hebrews / on the Word",
      "patristic",
      "The word is living and active. It does not lie on the page as a dead letter; it cuts, and the cut is mercy when it divides soul from pretense.",
      "Origen, on the piercing word",
    ),
    card(
      "John Calvin",
      "Commentary on Hebrews 4:12",
      "reformed",
      "None can hide from the word that searches. It is God’s own speech, and therefore it reaches the joints and marrow of the heart.",
      "Calvin, Comm. Heb. 4:12",
    ),
  ),
  "1JN-4-8": desk(
    card(
      "Augustine",
      "Tractates on 1 John 7",
      "patristic",
      "God is love: not that love is God as a mere affection, but that the God who is Trinity lives as love, and we know Him when we love.",
      "NPNF 1/7, Tractate 7 on 1 John",
    ),
    card(
      "John Calvin",
      "Commentary on 1 John 4:8",
      "reformed",
      "They who do not love do not know God, whatever their confession. Knowledge without love is a lie against this verse.",
      "Calvin, Comm. 1 John 4:8",
    ),
  ),
  "REV-21-1": desk(
    card(
      "Irenaeus",
      "Against Heresies 5.36",
      "patristic",
      "A new heaven and a new earth: not the abolition of creation, but its renewal, that the promise to Abraham might have a place to stand.",
      "Irenaeus, Adv. Haer. 5.36",
    ),
    card(
      "Andrew of Caesarea",
      "Commentary on Revelation 21",
      "orthodox",
      "The sea is no more — the figure of tumult. The city that comes down is not built by us; it is given.",
      "Andrew of Caesarea, In Apocalypsin 21",
    ),
    card(
      "John Calvin",
      "Commentary on 2 Peter / on last things",
      "reformed",
      "The restoration is cosmic, not merely inward. Hope that stops at the soul’s peace has not yet read the last pages.",
      "Calvin, on the new creation",
    ),
  ),
};

export const CURATED_ENTRIES: CuratedReceptionEntry[] = [
  // Matthew 1:21-23
  {
    verseRef: "MAT.1.21",
    sourceId: "chrysostom-matthew",
    excerpt: "He shall save His people; not the Jewish people only, but the whole world that comes to Him. He says not 'from visible enemies or tyrants,' but 'from their sins' — a warfare of soul, requiring divine power.",
    theologicalNote: "Chrysostom emphasizes the angelic announcement distinguishing Christ's spiritual salvation from nationalistic messianic expectations.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily IV)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 4 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.1.21",
    sourceId: "calvin-harmony-matthew",
    excerpt: "The name Jesus signifies Savior. The angel announces that He will redeem His people from their sins, correcting the common error of the Jews who looked for an earthly monarch to deliver them from Roman servitude.",
    theologicalNote: "Calvin highlights Christ as Savior from spiritual guilt and bondage, refuting carnal expectations of a temporal kingdom.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 1:21",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },
  {
    verseRef: "MAT.1.21",
    sourceId: "poole-annotations-matthew",
    excerpt: "His name is called Jesus, a Savior, because he saves from the guilt, power, and punishment of sin; not by a temporal deliverance, but by eternal redemption.",
    theologicalNote: "Poole expounds the triple deliverance of justification, sanctification, and glorification.",
    voice: "Matthew Poole",
    work: "Annotations upon the Holy Bible",
    tradition: "puritan",
    citation: "Poole, Annotations on Matt. 1:21",
    url: "https://www.ccel.org/ccel/poole/annotations.html",
  },
  {
    verseRef: "MAT.1.22",
    sourceId: "aquinas-catena-matthew",
    excerpt: "Jerome says: 'That it might be fulfilled which was spoken of the Lord by the prophet. Not that the event happened only that the prophecy might be fulfilled, but that the prophet foresaw the future and the divine decree was accomplished.'",
    theologicalNote: "Scholastic synthesis on divine sovereignty, prophecy, and teleological fulfillment in Christ.",
    voice: "Thomas Aquinas",
    work: "Catena Aurea on Matthew",
    tradition: "scholastic",
    citation: "Aquinas, Catena Aurea, Matt. 1:22",
    url: "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
  },
  {
    verseRef: "MAT.1.23",
    sourceId: "aquinas-catena-matthew",
    excerpt: "Jerome says: The Hebrew word alma signifies a virgin hidden and kept secret. Augustine adds: She who conceived without concupiscence remained a virgin in bearing and after bearing. He is truly Immanuel, God with us in the assumption of our flesh.",
    theologicalNote: "Aquinas compiles Patristic consensus from Jerome and Augustine affirming the perpetual virginity and the hypostatic union in Isaiah 7:14.",
    voice: "Thomas Aquinas",
    work: "Catena Aurea on Matthew",
    tradition: "scholastic",
    citation: "Aquinas, Catena Aurea, Matt. 1:22–23",
    url: "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
  },
  {
    verseRef: "MAT.1.23",
    sourceId: "chrysostom-matthew",
    excerpt: "They shall call His name Immanuel, which is, God with us. He did not say 'thou shalt call,' but 'they shall call' — that is, the events and deeds shall proclaim Him God with us.",
    theologicalNote: "Chrysostom on the divine identity of the incarnate Word manifest in His works.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily V)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 5 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.1.23",
    sourceId: "calvin-harmony-matthew",
    excerpt: "God has descended to us that we might ascend to Him; by taking our flesh He has united our lowliness with the divine majesty. Immanuel is not a bare title, but the substance of our salvation.",
    theologicalNote: "Calvin on the mediator uniting divine majesty with human flesh.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 1:23",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },
  {
    verseRef: "MAT.1.23",
    sourceId: "poole-annotations-matthew",
    excerpt: "Immanuel: God with us, not only by his essential presence, but by personal union, God and man in one person; and covenantally, reconciling God to man by his blood.",
    theologicalNote: "Poole expounds Immanuel as the mediator of the covenant of grace in two natures.",
    voice: "Matthew Poole",
    work: "Annotations upon the Holy Bible",
    tradition: "puritan",
    citation: "Poole, Annotations on Matt. 1:23",
    url: "https://www.ccel.org/ccel/poole/annotations.html",
  },

  // Matthew 5:3-10, 17-20
  {
    verseRef: "MAT.5.3",
    sourceId: "chrysostom-matthew",
    excerpt: "What is 'poor in spirit'? The humble and contrite in mind. As pride was the root of all wickedness, Christ sets humility as the first foundation of virtue; unless this be laid, whatever virtues you build will fall.",
    theologicalNote: "Humility as the foundation of virtue.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily XV)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 15 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.5.3",
    sourceId: "aquinas-catena-matthew",
    excerpt: "Augustine explains: The proud seek after an earthly kingdom; the poor in spirit, who are not puffed up with the pride of riches or knowledge, possess the kingdom of heaven. Jerome adds: Those who are voluntary in poverty for the Spirit's sake.",
    theologicalNote: "Interior detachment and poverty of spirit over self-glory.",
    voice: "Thomas Aquinas",
    work: "Catena Aurea on Matthew",
    tradition: "scholastic",
    citation: "Aquinas, Catena Aurea, Matt. 5:3",
    url: "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
  },
  {
    verseRef: "MAT.5.3",
    sourceId: "calvin-harmony-matthew",
    excerpt: "Those are poor in spirit who, brought to nothing in themselves and terrified by the consciousness of their spiritual poverty, betake themselves to the mercy of God. For grace is poured only into empty vessels.",
    theologicalNote: "Radical reduction to self-despair to receive sovereign grace.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 5:3",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },
  {
    verseRef: "MAT.5.3",
    sourceId: "luther-sermon-mount",
    excerpt: "To be poor in spirit does not mean begging or walking barefoot, but holding oneself destitute before God, having no trust in one's own righteousness, and clinging solely to Christ's promise by faith.",
    theologicalNote: "Faith grasping Christ outside human boasting.",
    voice: "Martin Luther",
    work: "Commentary on the Sermon on the Mount",
    tradition: "lutheran",
    citation: "Luther, Comm. Sermon on the Mount (1532), Matt. 5:3",
    url: "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
  },
  {
    verseRef: "MAT.5.17",
    sourceId: "augustine-sermon-mount",
    excerpt: "He fulfills the law either by doing what it commanded, or by supplying what was lacking, or by granting grace whereby its righteousness might be lived. The Law was given to convict; grace is given to fulfill.",
    theologicalNote: "The Law reveals transgressions and convicts; grace enables true spiritual fulfillment through love.",
    voice: "Augustine",
    work: "Our Lord's Sermon on the Mount 1.8",
    tradition: "western-patristic",
    citation: "NPNF 1/6, De Sermone Domini 1.8",
    url: "https://www.ccel.org/ccel/schaff/npnf106.html",
  },
  {
    verseRef: "MAT.5.17",
    sourceId: "calvin-harmony-matthew",
    excerpt: "Christ confirms the permanent authority of the Law. The doctrine of the Gospel does not detract from the Law, but establishes its true scope. Christ fulfills it by his perfect obedience, by his expiation on the cross, and by writing it on our hearts.",
    theologicalNote: "Harmony of Law and Gospel; three uses of the Law.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 5:17",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },
  {
    verseRef: "MAT.5.17",
    sourceId: "luther-sermon-mount",
    excerpt: "Christ alone fulfills the demands of the Law on our behalf, bearing its curse and rendering the full satisfaction that no sinner could ever yield. Hence our righteousness is alien, found in Him alone.",
    theologicalNote: "Active and passive obedience of Christ fulfilling the Law for justification.",
    voice: "Martin Luther",
    work: "Commentary on the Sermon on the Mount",
    tradition: "lutheran",
    citation: "Luther, Comm. Sermon on the Mount (1532), Matt. 5:17",
    url: "https://ccel.org/ccel/luther/good_works/good_works.ii.html",
  },

  // Matthew 16:16-18
  {
    verseRef: "MAT.16.16",
    sourceId: "chrysostom-matthew",
    excerpt: "Peter confesses: 'Thou art the Christ, the Son of the living God.' He says not 'a son' by grace, but 'the Son' by nature, declaring His eternal and proper deity.",
    theologicalNote: "Peter confesses Christ's genuine Sonship by divine nature.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily LIV)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 54 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.16.18",
    sourceId: "chrysostom-matthew",
    excerpt: "'On this rock I will build my church' — that is, on the faith of his confession. He did not say upon Peter, for he built His church not on a man, but on the faith of confessing Him as the Son of God.",
    theologicalNote: "The rock is the faith of Peter's confession.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily LIV)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 54 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.16.18",
    sourceId: "aquinas-catena-matthew",
    excerpt: "Augustine in his Retractations says: 'The rock was Christ, whom Simon confessed.' Yet Hilary and Leo show Peter rewarded for confessing Christ's divinity with apostolic primacy, that the unity of the Church might be preserved against the gates of hell.",
    theologicalNote: "Aquinas compiles Latin and Greek consensus synthesizing Christ as the foundational rock and Peter's confession.",
    voice: "Thomas Aquinas",
    work: "Catena Aurea on Matthew",
    tradition: "scholastic",
    citation: "Aquinas, Catena Aurea, Matt. 16:18",
    url: "https://www.ccel.org/ccel/aquinas/catena1.ii.xi.html",
  },
  {
    verseRef: "MAT.16.18",
    sourceId: "calvin-harmony-matthew",
    excerpt: "Christ applies the title of rock not to Peter's person, but to the confession of faith which he uttered. Christ is the only foundation; whoever rests on Peter's person rather than on Christ confesses a mortal foundation that cannot withstand the gates of hell.",
    theologicalNote: "Exegetes the rock as Christ and the confession of Him, refuting papal succession.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 16:18",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },

  // Matthew 28:18-20
  {
    verseRef: "MAT.28.18",
    sourceId: "chrysostom-matthew",
    excerpt: "'All power is given unto me in heaven and in earth.' He speaks this according to His human nature, which He assumed for our salvation; as God He possessed all things eternally, but now as our victorious Head He receives all dominion.",
    theologicalNote: "Apostolic empowerment and divine omnipresence.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily XC)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 90 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.28.18",
    sourceId: "calvin-harmony-matthew",
    excerpt: "Christ claims universal dominion over heaven and earth, not that He began to reign only then as God, but that as Mediator He was inaugurated as King over all creatures. By this authority He commissions the preaching of the Word and the administration of Sacraments.",
    theologicalNote: "The universal domain of Christ and the authority of Word and Sacraments.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 28:18–20",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },
  {
    verseRef: "MAT.28.20",
    sourceId: "chrysostom-matthew",
    excerpt: "'Lo, I am with you always, even unto the end of the world.' Do you mark His power and authority? He speaks not to the disciples only, but to all who should believe after them. He is present not by bodily appearance, but by divine majesty and grace.",
    theologicalNote: "Apostolic empowerment and divine omnipresence continuing to the consummation.",
    voice: "John Chrysostom",
    work: "Homilies on Matthew (Homily XC)",
    tradition: "eastern-patristic",
    citation: "NPNF 1/10, Homily 90 on Matthew",
    url: "https://www.ccel.org/ccel/schaff/npnf110.html",
  },
  {
    verseRef: "MAT.28.20",
    sourceId: "calvin-harmony-matthew",
    excerpt: "Christ promises that He will never abandon His church. Though removed from our sight into heaven, He is present by the power of His Spirit to defend and preserve His people against all adversaries.",
    theologicalNote: "Perpetual spiritual presence of Christ sustaining the Church.",
    voice: "John Calvin",
    work: "Commentary on a Harmony of the Evangelists",
    tradition: "reformed",
    citation: "Calvin, Comm. Matt. 28:20",
    url: "https://ccel.org/ccel/calvin/calcom31/calcom31.i.html",
  },
];

export function getCurated(
  bookId: string,
  chapter: number,
  verse: number | null,
): ReceptionResult | null {
  if (verse == null) {
    const chapterKey = `${bookId}-${chapter}`;
    if (curated[chapterKey]) return curated[chapterKey];

    // Fallback: gather curated cards across this chapter
    const prefixDash = `${bookId}-${chapter}-`;
    const prefixDot = `${bookId}.${chapter}.`;
    const chapterCards: SourceCard[] = [];
    const seen = new Set<string>();

    for (const [key, res] of Object.entries(curated)) {
      if (key.startsWith(prefixDash) || key.startsWith(prefixDot)) {
        for (const c of res.cards) {
          const sig = `${c.voice}-${c.work}-${c.citation}`;
          if (!seen.has(sig)) {
            seen.add(sig);
            chapterCards.push(c);
          }
        }
      }
    }
    if (chapterCards.length > 0) {
      return {
        source: "curated",
        caution: CAUTION,
        cards: chapterCards,
      };
    }
    return null;
  }

  return (
    curated[`${bookId}-${chapter}-${verse}`] ??
    curated[`${bookId}.${chapter}.${verse}`] ??
    null
  );
}

export function hasCurated(
  bookId: string,
  chapter: number,
  verse: number,
): boolean {
  return Boolean(
    curated[`${bookId}-${chapter}-${verse}`] ??
      curated[`${bookId}.${chapter}.${verse}`],
  );
}

export function markedVerses(bookId: string, chapter: number): number[] {
  const prefixDash = `${bookId}-${chapter}-`;
  const prefixDot = `${bookId}.${chapter}.`;
  const verses = new Set<number>();

  for (const k of Object.keys(curated)) {
    if (k.startsWith(prefixDash)) {
      const n = Number(k.slice(prefixDash.length));
      if (Number.isFinite(n)) verses.add(n);
    } else if (k.startsWith(prefixDot)) {
      const n = Number(k.slice(prefixDot.length));
      if (Number.isFinite(n)) verses.add(n);
    }
  }

  return Array.from(verses).sort((a, b) => a - b);
}

export function curatedBookIds(): Set<string> {
  const ids = new Set<string>();
  for (const k of Object.keys(curated)) {
    const id = k.split("-")[0];
    if (id) ids.add(id);
  }
  return ids;
}
