import type { Chapter } from "./types";

const WEB = "World English Bible";
const NOTE = "World English Bible. Public domain.";

function pack(
  bookId: string,
  bookName: string,
  chapter: number,
  reference: string,
  texts: string[],
): Chapter {
  return {
    reference,
    bookId,
    bookName,
    chapter,
    translationName: WEB,
    translationNote: NOTE,
    verses: texts.map((text, i) => ({
      bookId,
      bookName,
      chapter,
      verse: i + 1,
      text,
    })),
  };
}

const SEED: Record<string, Chapter> = {
  "JHN-1": pack("JHN", "John", 1, "John 1", [
    "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "The same was in the beginning with God.",
    "All things were made through him. Without him was not anything made that has been made.",
    "In him was life, and the life was the light of men.",
    "The light shines in the darkness, and the darkness hasn’t overcome it.",
    "There came a man, sent from God, whose name was John.",
    "The same came as a witness, that he might testify about the light, that all might believe through him.",
    "He was not the light, but was sent that he might testify about the light.",
    "The true light that enlightens everyone was coming into the world.",
    "He was in the world, and the world was made through him, and the world didn’t recognize him.",
    "He came to his own, and those who were his own didn’t receive him.",
    "But as many as received him, to them he gave the right to become God’s children, to those who believe in his name:",
    "who were born not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
    "The Word became flesh, and lived among us. We saw his glory, such glory as of the one and only Son of the Father, full of grace and truth.",
    "John testified about him. He cried out, saying, “This was he of whom I said, ‘He who comes after me has surpassed me, for he was before me.’”",
    "From his fullness we all received grace upon grace.",
    "For the law was given through Moses. Grace and truth were realized through Jesus Christ.",
    "No one has seen God at any time. The one and only Son, who is in the bosom of the Father, he has declared him.",
    "This is John’s testimony, when the Jews sent priests and Levites from Jerusalem to ask him, “Who are you?”",
    "He declared, and didn’t deny, but he declared, “I am not the Christ.”",
    "They asked him, “What then? Are you Elijah?” He said, “I am not.” “Are you the prophet?” He answered, “No.”",
    "They said therefore to him, “Who are you? Give us an answer to take back to those who sent us. What do you say about yourself?”",
    "He said, “I am the voice of one crying in the wilderness, ‘Make straight the way of the Lord,’ as Isaiah the prophet said.”",
    "The ones who had been sent were from the Pharisees.",
    "They asked him, “Why then do you baptize, if you are not the Christ, nor Elijah, nor the prophet?”",
    "John answered them, “I baptize in water, but among you stands one whom you don’t know.",
    "He is the one who comes after me, who is preferred before me, whose sandal strap I’m not worthy to loosen.”",
    "These things were done in Bethany beyond the Jordan, where John was baptizing.",
    "The next day, he saw Jesus coming to him, and said, “Behold, the Lamb of God, who takes away the sin of the world!",
    "This is he of whom I said, ‘After me comes a man who is preferred before me, for he was before me.’",
    "I didn’t know him, but for this reason I came baptizing in water: that he would be revealed to Israel.”",
    "John testified, saying, “I have seen the Spirit descending like a dove out of heaven, and it remained on him.",
    "I didn’t recognize him, but he who sent me to baptize in water, he said to me, ‘On whomever you will see the Spirit descending, and remaining on him, the same is he who baptizes in the Holy Spirit.’",
    "I have seen, and have testified that this is the Son of God.”",
    "Again, the next day, John was standing with two of his disciples,",
    "and he looked at Jesus as he walked, and said, “Behold, the Lamb of God!”",
    "The two disciples heard him speak, and they followed Jesus.",
    "Jesus turned, and saw them following, and said to them, “What are you looking for?” They said to him, “Rabbi” (which is to say, being interpreted, Teacher), “where are you staying?”",
    "He said to them, “Come, and see.” They came and saw where he was staying, and they stayed with him that day. It was about the tenth hour.",
    "One of the two who heard John, and followed him, was Andrew, Simon Peter’s brother.",
    "He first found his own brother, Simon, and said to him, “We have found the Messiah!” (which is, being interpreted, Christ).",
    "He brought him to Jesus. Jesus looked at him, and said, “You are Simon the son of Jonah. You shall be called Cephas” (which is by interpretation, Peter).",
    "On the next day, he was determined to go out into Galilee, and he found Philip. Jesus said to him, “Follow me.”",
    "Now Philip was from Bethsaida, of the city of Andrew and Peter.",
    "Philip found Nathanael, and said to him, “We have found him, of whom Moses in the law, and the prophets, wrote: Jesus of Nazareth, the son of Joseph.”",
    "Nathanael said to him, “Can any good thing come out of Nazareth?” Philip said to him, “Come and see.”",
    "Jesus saw Nathanael coming to him, and said about him, “Behold, an Israelite indeed, in whom is no deceit!”",
    "Nathanael said to him, “How do you know me?” Jesus answered him, “Before Philip called you, when you were under the fig tree, I saw you.”",
    "Nathanael answered him, “Rabbi, you are the Son of God! You are King of Israel!”",
    "Jesus answered him, “Because I told you, ‘I saw you underneath the fig tree,’ do you believe? You will see greater things than these!”",
    "He said to him, “Most certainly, I tell you all, hereafter you will see heaven opened, and the angels of God ascending and descending on the Son of Man.”",
  ]),
  "GEN-1": pack("GEN", "Genesis", 1, "Genesis 1", [
    "In the beginning, God created the heavens and the earth.",
    "The earth was formless and empty. Darkness was on the surface of the deep and God’s Spirit was hovering over the surface of the waters.",
    "God said, “Let there be light,” and there was light.",
    "God saw the light, and saw that it was good. God divided the light from the darkness.",
    "God called the light “day”, and the darkness he called “night”. There was evening and there was morning, the first day.",
    "God said, “Let there be an expanse in the middle of the waters, and let it divide the waters from the waters.”",
    "God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so.",
    "God called the expanse “sky”. There was evening and there was morning, a second day.",
    "God said, “Let the waters under the sky be gathered together to one place, and let the dry land appear”; and it was so.",
    "God called the dry land “earth”, and the gathering together of the waters he called “seas”. God saw that it was good.",
    "God said, “Let the earth yield grass, herbs yielding seeds, and fruit trees bearing fruit after their kind, with their seeds in it, on the earth”; and it was so.",
    "The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seeds in it, after their kind; and God saw that it was good.",
    "There was evening and there was morning, a third day.",
    "God said, “Let there be lights in the expanse of the sky to divide the day from the night; and let them be for signs to mark seasons, days, and years;",
    "and let them be for lights in the expanse of the sky to give light on the earth”; and it was so.",
    "God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars.",
    "God set them in the expanse of the sky to give light to the earth,",
    "and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good.",
    "There was evening and there was morning, a fourth day.",
    "God said, “Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of the sky.”",
    "God created the large sea creatures and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good.",
    "God blessed them, saying, “Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth.”",
    "There was evening and there was morning, a fifth day.",
    "God said, “Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind”; and it was so.",
    "God made the animals of the earth after their kind, and the livestock after their kind, and everything that creeps on the ground after its kind. God saw that it was good.",
    "God said, “Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth.”",
    "God created man in his own image. In God’s image he created him; male and female he created them.",
    "God blessed them. God said to them, “Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth.”",
    "God said, “Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food.",
    "To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;” and it was so.",
    "God saw everything that he had made, and, behold, it was very good. There was evening and there was morning, a sixth day.",
  ]),
  "ROM-8": pack("ROM", "Romans", 8, "Romans 8", [
    "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit.",
    "For the law of the Spirit of life in Christ Jesus made me free from the law of sin and of death.",
    "For what the law couldn’t do, in that it was weak through the flesh, God did, sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh;",
    "that the ordinance of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.",
    "For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit.",
    "For the mind of the flesh is death, but the mind of the Spirit is life and peace;",
    "because the mind of the flesh is hostile towards God; for it is not subject to God’s law, neither indeed can it be.",
    "Those who are in the flesh can’t please God.",
    "But you are not in the flesh but in the Spirit, if it is so that the Spirit of God dwells in you. But if any man doesn’t have the Spirit of Christ, he is not his.",
    "If Christ is in you, the body is dead because of sin, but the spirit is alive because of righteousness.",
    "But if the Spirit of him who raised up Jesus from the dead dwells in you, he who raised up Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you.",
    "So then, brothers, we are debtors, not to the flesh, to live after the flesh.",
    "For if you live after the flesh, you must die; but if by the Spirit you put to death the deeds of the body, you will live.",
    "For as many as are led by the Spirit of God, these are children of God.",
    "For you didn’t receive the spirit of bondage again to fear, but you received the Spirit of adoption, by whom we cry, “Abba! Father!”",
    "The Spirit himself testifies with our spirit that we are children of God;",
    "and if children, then heirs; heirs of God, and joint heirs with Christ; if indeed we suffer with him, that we may also be glorified with him.",
    "For I consider that the sufferings of this present time are not worthy to be compared with the glory which will be revealed toward us.",
    "For the creation waits with eager expectation for the children of God to be revealed.",
    "For the creation was subjected to vanity, not of its own will, but because of him who subjected it, in hope",
    "that the creation itself also will be delivered from the bondage of decay into the liberty of the glory of the children of God.",
    "For we know that the whole creation groans and travails in pain together until now.",
    "Not only so, but ourselves also, who have the first fruits of the Spirit, even we ourselves groan within ourselves, waiting for adoption, the redemption of our body.",
    "For we were saved in hope, but hope that is seen is not hope. For who hopes for that which he sees?",
    "But if we hope for that which we don’t see, we wait for it with patience.",
    "In the same way, the Spirit also helps our weaknesses, for we don’t know how to pray as we ought. But the Spirit himself makes intercession for us with groanings which can’t be uttered.",
    "He who searches the hearts knows what is on the Spirit’s mind, because he makes intercession for the saints according to God.",
    "We know that all things work together for good for those who love God, to those who are called according to his purpose.",
    "For whom he foreknew, he also predestined to be conformed to the image of his Son, that he might be the firstborn among many brothers.",
    "Whom he predestined, those he also called. Whom he called, those he also justified. Whom he justified, those he also glorified.",
    "What then shall we say about these things? If God is for us, who can be against us?",
    "He who didn’t spare his own Son, but delivered him up for us all, how would he not also with him freely give us all things?",
    "Who could bring a charge against God’s chosen ones? It is God who justifies.",
    "Who is he who condemns? It is Christ who died, yes rather, who was raised from the dead, who is at the right hand of God, who also makes intercession for us.",
    "Who shall separate us from the love of Christ? Could oppression, or anguish, or persecution, or famine, or nakedness, or peril, or sword?",
    "Even as it is written, “For your sake we are killed all day long. We were accounted as sheep for the slaughter.”",
    "No, in all these things, we are more than conquerors through him who loved us.",
    "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers,",
    "nor height, nor depth, nor any other created thing, will be able to separate us from God’s love, which is in Christ Jesus our Lord.",
  ]),
  "PSA-119": pack("PSA", "Psalms", 119, "Psalms 119", [
    "Blessed are those whose ways are blameless, who walk according to Yahweh’s law.",
    "Blessed are those who keep his statutes, who seek him with their whole heart.",
    "Yes, they do nothing wrong. They walk in his ways.",
    "You have commanded your precepts, that we should fully obey them.",
    "Oh that my ways were steadfast to obey your statutes!",
    "Then I wouldn’t be disappointed, when I consider all of your commandments.",
    "I will give thanks to you with uprightness of heart, when I learn your righteous judgments.",
    "I will observe your statutes. Don’t utterly forsake me.",
    "How can a young man keep his way pure? By living according to your word.",
    "With my whole heart, I have sought you. Don’t let me wander from your commandments.",
    "I have hidden your word in my heart, that I might not sin against you.",
    "Blessed are you, Yahweh. Teach me your statutes.",
    "With my lips, I have declared all the ordinances of your mouth.",
    "I have rejoiced in the way of your testimonies, as much as in all riches.",
    "I will meditate on your precepts, and consider your ways.",
    "I will delight myself in your statutes. I will not forget your word.",
    "Do good to your servant. I will live and I will obey your word.",
    "Open my eyes, that I may see wondrous things out of your law.",
    "I am a stranger on the earth. Don’t hide your commandments from me.",
    "My soul is consumed with longing for your ordinances at all times.",
    "You have rebuked the proud who are cursed, who wander from your commandments.",
    "Take reproach and contempt away from me, for I have kept your statutes.",
    "Though princes sit and slander me, your servant will meditate on your statutes.",
    "Indeed your statutes are my delight, and my counselors.",
    "My soul is laid low in the dust. Revive me according to your word!",
    "I declared my ways, and you answered me. Teach me your statutes.",
    "Let me understand the teaching of your precepts! Then I will meditate on your wondrous works.",
    "My soul is weary with sorrow: strengthen me according to your word.",
    "Keep me from the way of deceit. Grant me your law graciously!",
    "I have chosen the way of truth. I have set your ordinances before me.",
    "I cling to your statutes, Yahweh. Don’t let me be disappointed.",
    "I run in the path of your commandments, for you have set my heart free.",
    "Teach me, Yahweh, the way of your statutes. I will keep them to the end.",
    "Give me understanding, and I will keep your law. Yes, I will obey it with my whole heart.",
    "Direct me in the path of your commandments, for I delight in them.",
    "Turn my heart toward your statutes, not toward selfish gain.",
    "Turn my eyes away from looking at worthless things. Revive me in your ways.",
    "Fulfill your promise to your servant, that you may be feared.",
    "Take away my disgrace that I dread, for your ordinances are good.",
    "Behold, I long for your precepts! Revive me in your righteousness.",
    "Let your loving kindness also come to me, Yahweh, your salvation, according to your word.",
    "So I will have an answer for him who reproaches me, for I trust in your word.",
    "Don’t snatch the word of truth out of my mouth, for I put my hope in your ordinances.",
    "So I will obey your law continually, forever and ever.",
    "I will walk in liberty, for I have sought your precepts.",
    "I will also speak of your statutes before kings, and will not be disappointed.",
    "I will delight myself in your commandments, because I love them.",
    "I reach out my hands for your commandments, which I love. I will meditate on your statutes.",
    "Remember your word to your servant, because you gave me hope.",
    "This is my comfort in my affliction, for your word has revived me.",
    "The arrogant mock me excessively, but I don’t swerve from your law.",
    "I remember your ordinances of old, Yahweh, and have comforted myself.",
    "Indignation has taken hold on me, because of the wicked who forsake your law.",
    "Your statutes have been my songs, in the house where I live.",
    "I have remembered your name, Yahweh, in the night, and I obey your law.",
    "This is my way, that I keep your precepts.",
    "Yahweh is my portion. I promised to obey your words.",
    "I sought your favor with my whole heart. Be merciful to me according to your word.",
    "I considered my ways, and turned my steps to your statutes.",
    "I will hurry, and not delay, to obey your commandments.",
    "The ropes of the wicked bind me, but I won’t forget your law.",
    "At midnight I will rise to give thanks to you, because of your righteous ordinances.",
    "I am a friend of all those who fear you, of those who observe your precepts.",
    "The earth is full of your loving kindness, Yahweh. Teach me your statutes.",
    "Do good to your servant, according to your word, Yahweh.",
    "Teach me good judgment and knowledge, for I believe in your commandments.",
    "Before I was afflicted, I went astray; but now I observe your word.",
    "You are good, and do good. Teach me your statutes.",
    "The proud have smeared a lie upon me. With my whole heart, I will keep your precepts.",
    "Their heart is as callous as the fat, but I delight in your law.",
    "It is good for me that I have been afflicted, that I may learn your statutes.",
    "The law of your mouth is better to me than thousands of pieces of gold and silver.",
    "Your hands have made me and formed me. Give me understanding, that I may learn your commandments.",
    "Those who fear you will see me and be glad, because I have put my hope in your word.",
    "Yahweh, I know that your judgments are righteous, that in faithfulness you have afflicted me.",
    "Please let your loving kindness be for my comfort, according to your word to your servant.",
    "Let your tender mercies come to me, that I may live; for your law is my delight.",
    "Let the proud be disappointed, for they have overthrown me wrongfully. I will meditate on your precepts.",
    "Let those who fear you turn to me. They will know your statutes.",
    "Let my heart be blameless toward your decrees, that I may not be disappointed.",
    "My soul faints for your salvation. I hope in your word.",
    "My eyes fail for your word. I say, “When will you comfort me?”",
    "For I have become like a wineskin in the smoke. I don’t forget your statutes.",
    "How many are the days of your servant? When will you execute judgment on those who persecute me?",
    "The proud have dug pits for me, contrary to your law.",
    "All of your commandments are faithful. They persecute me wrongfully. Help me!",
    "They had almost wiped me from the earth, but I didn’t forsake your precepts.",
    "Preserve my life according to your loving kindness, so I will obey the statutes of your mouth.",
    "Yahweh, your word is settled in heaven forever.",
    "Your faithfulness is to all generations. You have established the earth, and it remains.",
    "Your laws remain to this day, for all things serve you.",
    "Unless your law had been my delight, I would have perished in my affliction.",
    "I will never forget your precepts, for with them, you have revived me.",
    "I am yours. Save me, for I have sought your precepts.",
    "The wicked have waited for me, to destroy me. I will consider your statutes.",
    "I have seen a limit to all perfection, but your commands are boundless.",
    "How I love your law! It is my meditation all day.",
    "Your commandments make me wiser than my enemies, for your commandments are always with me.",
    "I have more understanding than all my teachers, for your testimonies are my meditation.",
    "I understand more than the aged, because I have kept your precepts.",
    "I have kept my feet from every evil way, that I might observe your word.",
    "I have not turned away from your ordinances, for you have taught me.",
    "How sweet are your promises to my taste, more than honey to my mouth!",
    "Through your precepts, I get understanding; therefore I hate every false way.",
    "Your word is a lamp to my feet, and a light for my path.",
    "I have sworn, and have confirmed it, that I will obey your righteous ordinances.",
    "I am afflicted very much. Revive me, Yahweh, according to your word.",
    "Accept, I beg you, the willing offerings of my mouth. Yahweh, teach me your ordinances.",
    "My soul is continually in my hand, yet I won’t forget your law.",
    "The wicked have laid a snare for me, yet I haven’t gone astray from your precepts.",
    "I have taken your testimonies as a heritage forever, for they are the joy of my heart.",
    "I have set my heart to perform your statutes forever, even to the end.",
    "I hate double-minded men, but I love your law.",
    "You are my hiding place and my shield. I hope in your word.",
    "Depart from me, you evildoers, that I may keep the commandments of my God.",
    "Uphold me according to your word, that I may live. Let me not be ashamed of my hope.",
    "Hold me up, and I will be safe, and will have respect for your statutes continually.",
    "You reject all those who stray from your statutes, for their deceit is in vain.",
    "You put away all the wicked of the earth like dross. Therefore I love your testimonies.",
    "My flesh trembles for fear of you. I am afraid of your judgments.",
    "I have done what is just and righteous. Don’t leave me to my oppressors.",
    "Ensure your servant’s well-being. Don’t let the proud oppress me.",
    "My eyes fail looking for your salvation, for your righteous word.",
    "Deal with your servant according to your loving kindness. Teach me your statutes.",
    "I am your servant. Give me understanding, that I may know your testimonies.",
    "It is time to act, Yahweh, for they break your law.",
    "Therefore I love your commandments more than gold, yes, more than pure gold.",
    "Therefore I consider all of your precepts to be right. I hate every false way.",
    "Your testimonies are wonderful, therefore my soul keeps them.",
    "The entrance of your words gives light. It gives understanding to the simple.",
    "I opened my mouth wide and panted, for I longed for your commandments.",
    "Turn to me, and have mercy on me, as you always do to those who love your name.",
    "Establish my footsteps in your word. Don’t let any iniquity have dominion over me.",
    "Redeem me from the oppression of man, so I will observe your precepts.",
    "Make your face shine on your servant. Teach me your statutes.",
    "Streams of tears run down my eyes, because they don’t observe your law.",
    "You are righteous, Yahweh. Your judgments are upright.",
    "You have commanded your statutes in righteousness. They are fully trustworthy.",
    "My zeal wears me out, because my enemies ignore your words.",
    "Your promises have been thoroughly tested, and your servant loves them.",
    "I am small and despised. I don’t forget your precepts.",
    "Your righteousness is an everlasting righteousness. Your law is truth.",
    "Trouble and anguish have taken hold of me. Your commandments are my delight.",
    "Your testimonies are righteous forever. Give me understanding, that I may live.",
    "I have called with my whole heart. Answer me, Yahweh! I will keep your statutes.",
    "I have called to you. Save me! I will obey your statutes.",
    "I rise before dawn and cry for help. I put my hope in your words.",
    "My eyes stay open through the night watches, that I might meditate on your word.",
    "Hear my voice according to your loving kindness. Revive me, Yahweh, according to your ordinances.",
    "They draw near who follow after wickedness. They are far from your law.",
    "You are near, Yahweh. All your commandments are truth.",
    "Of old I have known from your testimonies, that you have founded them forever.",
    "Consider my affliction, and deliver me, for I don’t forget your law.",
    "Plead my cause, and redeem me! Revive me according to your promise.",
    "Salvation is far from the wicked, for they don’t seek your statutes.",
    "Great are your tender mercies, Yahweh. Revive me according to your ordinances.",
    "Many are my persecutors and my adversaries. I haven’t swerved from your testimonies.",
    "I look at the faithless with loathing, because they don’t observe your word.",
    "Consider how I love your precepts. Revive me, Yahweh, according to your loving kindness.",
    "All of your words are truth. Every one of your righteous ordinances endures forever.",
    "Princes have persecuted me without a cause, but my heart stands in awe of your words.",
    "I rejoice at your word, as one who finds great plunder.",
    "I hate and abhor falsehood. I love your law.",
    "Seven times a day, I praise you, because of your righteous ordinances.",
    "Those who love your law have great peace. Nothing causes them to stumble.",
    "I have hoped for your salvation, Yahweh. I have done your commandments.",
    "My soul has observed your testimonies. I love them exceedingly.",
    "I have obeyed your precepts and your testimonies, for all my ways are before you.",
    "Let my cry come before you, Yahweh. Give me understanding according to your word.",
    "Let my supplication come before you. Deliver me according to your word.",
    "Let my lips utter praise, for you teach me your statutes.",
    "Let my tongue sing of your word, for all your commandments are righteousness.",
    "Let your hand be ready to help me, for I have chosen your precepts.",
    "I have longed for your salvation, Yahweh. Your law is my delight.",
    "Let my soul live, that I may praise you. Let your ordinances help me.",
    "I have gone astray like a lost sheep. Seek your servant, for I don’t forget your commandments.",
  ]),
};

export function getSeed(bookId: string, chapter: number): Chapter | null {
  return SEED[`${bookId}-${chapter}`] ?? null;
}
