import type { CatalogEntry } from "../catalog.ts";
import { buildPsalmsChapters } from "./wave-psalms.ts";

/**
 * OT wave builders, code-generated by ~/workspace/ot-waves/gen-waves.mjs.
 * Do not edit by hand — regenerate.
 * Staged rollout: Psalms only (Wave 2). Later waves append their builders here.
 */
export const OT_WAVE_BUILDERS: Array<
  (have: Set<string>) => CatalogEntry[]
> = [buildPsalmsChapters];
