import type { CatalogEntry } from "../catalog.ts";

/**
 * OT wave: psalms. Code-generated by ~/workspace/ot-waves/gen-waves.mjs
 * from psalms.json. Do not edit by hand — regenerate.
 */
const HENRY_PSALMS = ["ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x", "xi", "xii", "xiii", "xiv", "xv", "xvi", "xvii", "xviii", "xix", "xx", "xxi", "xxii", "xxiii", "xxiv", "xxv", "xxvi", "xxvii", "xxviii", "xxix", "xxx", "xxxi", "xxxii", "xxxiii", "xxxiv", "xxxv", "xxxvi", "xxxvii", "xxxviii", "xxxix", "xl", "xli", "xlii", "xliii", "xliv", "xlv", "xlvi", "xlvii", "xlviii", "xlix", "l", "li", "lii", "liii", "liv", "lv", "lvi", "lvii", "lviii", "lix", "lx", "lxi", "lxii", "lxiii", "lxiv", "lxv", "lxvi", "lxvii", "lxviii", "lxix", "lxx", "lxxi", "lxxii", "lxxiii", "lxxiv", "lxxv", "lxxvi", "lxxvii", "lxxviii", "lxxix", "lxxx", "lxxxi", "lxxxii", "lxxxiii", "lxxxiv", "lxxxv", "lxxxvi", "lxxxvii", "lxxxviii", "lxxxix", "xc", "xci", "xcii", "xciii", "xciv", "xcv", "xcvi", "xcvii", "xcviii", "xcix", "c", "ci", "cii", "ciii", "civ", "cv", "cvi", "cvii", "cviii", "cix", "cx", "cxi", "cxii", "cxiii", "cxiv", "cxv", "cxvi", "cxvii", "cxviii", "cxix", "cxx", "cxxi", "cxxii", "cxxiii", "cxxiv", "cxxv", "cxxvi", "cxxvii", "cxxviii", "cxxix", "cxxx", "cxxxi", "cxxxii", "cxxxiii", "cxxxiv", "cxxxv", "cxxxvi", "cxxxvii", "cxxxviii", "cxxxix", "cxl", "cxli", "cxlii", "cxliii", "cxliv", "cxlv", "cxlvi", "cxlvii", "cxlviii", "cxlix", "cl", "cli"];

export function buildPsalmsChapters(have: Set<string>): CatalogEntry[] {
  const out: CatalogEntry[] = [];
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("kad-psalms-" + ch)) continue;
    out.push({ id: "kad-psalms-" + ch, voice: "Keil & Delitzsch", work: "Commentary on the Old Testament", tradition: "lutheran", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/kad/psalms/${ch}.htm`, tags: ["psalms","kad","keil-delitzsch"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("henry-psalms-" + ch)) continue;
    out.push({ id: "henry-psalms-" + ch, voice: "Matthew Henry", work: "Commentary on the Whole Bible", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://ccel.org/ccel/henry/mhc3/mhc3.Ps.${HENRY_PSALMS[ch - 1]}.html`, tags: ["psalms","henry"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("gill-psalms-" + ch)) continue;
    const pad = String(ch).padStart(3, "0");
    out.push({ id: "gill-psalms-" + ch, voice: "John Gill", work: "Exposition of the Old and New Testament", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://archive.sacred-texts.com/bib/cmt/gill/psa${pad}.htm`, altUrl: `https://biblehub.com/commentaries/gill/psalms/${ch}.htm`, tags: ["psalms","gill","baptist"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("jfb-psalms-" + ch)) continue;
    const pad = String(ch).padStart(3, "0");
    out.push({ id: "jfb-psalms-" + ch, voice: "Jamieson-Fausset-Brown", work: "Commentary Critical and Explanatory on the Whole Bible", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://archive.sacred-texts.com/bib/cmt/jfb/psa${pad}.htm`, altUrl: `https://biblehub.com/commentaries/jfb/psalms/${ch}.htm`, tags: ["psalms","jfb"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("poole-psalms-" + ch)) continue;
    out.push({ id: "poole-psalms-" + ch, voice: "Matthew Poole", work: "Annotations upon the Holy Bible", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/poole/psalms/${ch}.htm`, tags: ["psalms","poole"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("clarke-psalms-" + ch)) continue;
    out.push({ id: "clarke-psalms-" + ch, voice: "Adam Clarke", work: "Clarke's Commentary on the Bible", tradition: "arminian", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/clarke/psalms/${ch}.htm`, tags: ["psalms","clarke","methodist"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("lange-psalms-" + ch)) continue;
    out.push({ id: "lange-psalms-" + ch, voice: "John Peter Lange", work: "Commentary on the Holy Scriptures", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/lange/psalms/${ch}.htm`, tags: ["psalms","lange"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("ellicott-psalms-" + ch)) continue;
    out.push({ id: "ellicott-psalms-" + ch, voice: "Charles Ellicott", work: "Commentary for English Readers", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/ellicott/psalms/${ch}.htm`, tags: ["psalms","ellicott"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("barnes-psalms-" + ch)) continue;
    out.push({ id: "barnes-psalms-" + ch, voice: "Albert Barnes", work: "Barnes' Notes on the Old Testament", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/barnes/psalms/${ch}.htm`, tags: ["psalms","barnes"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("cambridge-psalms-" + ch)) continue;
    out.push({ id: "cambridge-psalms-" + ch, voice: "Cambridge Bible", work: "Cambridge Bible for Schools and Colleges", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/cambridge/psalms/${ch}.htm`, tags: ["psalms","cambridge"], books: ["PSA"], chapters: [ch] });
  }
  for (let ch = 1; ch <= 150; ch++) {
    if (have.has("pulpit-psalms-" + ch)) continue;
    out.push({ id: "pulpit-psalms-" + ch, voice: "Pulpit Commentary", work: "The Pulpit Commentary", tradition: "reformed", locus: "Psalms" + " " + ch, url: `https://biblehub.com/commentaries/pulpit/psalms/${ch}.htm`, tags: ["psalms","pulpit"], books: ["PSA"], chapters: [ch] });
  }
  {
    const id = "augustine-psalms-1";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 1", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-i", tags: ["psalms","augustine","blessed"], books: ["PSA"], chapters: [1] });
  }
  {
    const id = "augustine-psalms-8";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 8", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-viii", tags: ["psalms","augustine","majesty"], books: ["PSA"], chapters: [8] });
  }
  {
    const id = "augustine-psalms-19";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 19", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xix", tags: ["psalms","augustine","creation"], books: ["PSA"], chapters: [19] });
  }
  {
    const id = "augustine-psalms-22";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 22", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xxii", tags: ["psalms","augustine","cross"], books: ["PSA"], chapters: [22] });
  }
  {
    const id = "augustine-psalms-23";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 23", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xxiii", tags: ["psalms","augustine","shepherd"], books: ["PSA"], chapters: [23] });
  }
  {
    const id = "augustine-psalms-42";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 42", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xlii", tags: ["psalms","augustine","thirst"], books: ["PSA"], chapters: [42] });
  }
  {
    const id = "augustine-psalms-46";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 46", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xlvi", tags: ["psalms","augustine","refuge"], books: ["PSA"], chapters: [46] });
  }
  {
    const id = "augustine-psalms-51";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 51", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-li", tags: ["psalms","augustine","penitence"], books: ["PSA"], chapters: [51] });
  }
  {
    const id = "augustine-psalms-90";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 90", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xc", tags: ["psalms","augustine","mortality"], books: ["PSA"], chapters: [90] });
  }
  {
    const id = "augustine-psalms-91";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 91", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-xci", tags: ["psalms","augustine","protection"], books: ["PSA"], chapters: [91] });
  }
  {
    const id = "augustine-psalms-110";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 110", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-cx", tags: ["psalms","augustine","priest-king"], books: ["PSA"], chapters: [110] });
  }
  {
    const id = "augustine-psalms-121";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 121", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-cxxi", tags: ["psalms","augustine","keeper"], books: ["PSA"], chapters: [121] });
  }
  {
    const id = "augustine-psalms-130";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 130", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-cxxx", tags: ["psalms","augustine","depths"], books: ["PSA"], chapters: [130] });
  }
  {
    const id = "augustine-psalms-133";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 133", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-cxxxiii", tags: ["psalms","augustine","unity"], books: ["PSA"], chapters: [133] });
  }
  {
    const id = "augustine-psalms-139";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 139", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-cxxxix", tags: ["psalms","augustine","omniscience"], books: ["PSA"], chapters: [139] });
  }
  {
    const id = "augustine-psalms-150";
    if (!have.has(id)) out.push({ id, voice: "Augustine", work: "Expositions of the Psalms", tradition: "patristic", locus: "Psalms 150", url: "https://sacred-texts.com/book/nicene-and-post-nicene-fathers-vol-viii/read/psalm-cl", tags: ["psalms","augustine","praise"], books: ["PSA"], chapters: [150] });
  }
  {
    const id = "spurgeon-psalms-1";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 1", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp1.htm", tags: ["psalms","spurgeon","blessed"], books: ["PSA"], chapters: [1] });
  }
  {
    const id = "spurgeon-psalms-8";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 8", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp8.htm", tags: ["psalms","spurgeon","majesty"], books: ["PSA"], chapters: [8] });
  }
  {
    const id = "spurgeon-psalms-19";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 19", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp19.htm", tags: ["psalms","spurgeon","creation"], books: ["PSA"], chapters: [19] });
  }
  {
    const id = "spurgeon-psalms-22";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 22", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp22.htm", tags: ["psalms","spurgeon","cross"], books: ["PSA"], chapters: [22] });
  }
  {
    const id = "spurgeon-psalms-23";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 23", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp23.htm", tags: ["psalms","spurgeon","shepherd"], books: ["PSA"], chapters: [23] });
  }
  {
    const id = "spurgeon-psalms-42";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 42", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp42.htm", tags: ["psalms","spurgeon","thirst"], books: ["PSA"], chapters: [42] });
  }
  {
    const id = "spurgeon-psalms-46";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 46", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp46.htm", tags: ["psalms","spurgeon","refuge"], books: ["PSA"], chapters: [46] });
  }
  {
    const id = "spurgeon-psalms-51";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 51", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp51.htm", tags: ["psalms","spurgeon","penitence"], books: ["PSA"], chapters: [51] });
  }
  {
    const id = "spurgeon-psalms-90";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 90", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp90.htm", tags: ["psalms","spurgeon","mortality"], books: ["PSA"], chapters: [90] });
  }
  {
    const id = "spurgeon-psalms-91";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 91", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp91.htm", tags: ["psalms","spurgeon","protection"], books: ["PSA"], chapters: [91] });
  }
  {
    const id = "spurgeon-psalms-110";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 110", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp110.htm", tags: ["psalms","spurgeon","priest-king"], books: ["PSA"], chapters: [110] });
  }
  {
    const id = "spurgeon-psalms-121";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 121", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp121.htm", tags: ["psalms","spurgeon","keeper"], books: ["PSA"], chapters: [121] });
  }
  {
    const id = "spurgeon-psalms-130";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 130", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp130.htm", tags: ["psalms","spurgeon","depths"], books: ["PSA"], chapters: [130] });
  }
  {
    const id = "spurgeon-psalms-133";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 133", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp133.htm", tags: ["psalms","spurgeon","unity"], books: ["PSA"], chapters: [133] });
  }
  {
    const id = "spurgeon-psalms-139";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 139", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp139.htm", tags: ["psalms","spurgeon","omniscience"], books: ["PSA"], chapters: [139] });
  }
  {
    const id = "spurgeon-psalms-150";
    if (!have.has(id)) out.push({ id, voice: "Charles Spurgeon", work: "Treasury of David", tradition: "reformed", locus: "Psalms 150", url: "https://www.biblebb.com/files/spurgeon/TOD/chstp150.htm", tags: ["psalms","spurgeon","praise"], books: ["PSA"], chapters: [150] });
  }
  return out;
}
